#!/usr/bin/with-contenv bash

if ! dpkg -s nautilus >/dev/null 2>&1; then
    PACKAGES="nautilus ${PACKAGES}"
fi

if [ -n "${PACKAGES}" ]; then
    echo "${PACKAGES}" >> /mod-repo-packages-to-install.list
    echo "**** Adding calibre filemanager application to package install list ****"
else
    echo "**** Calibre filemanager application already installed, skipping ****"
fi



